### ISSUE TITLE
InternalException : null since 12th July 2018

### ISSUE THREAD

**Issue by ravithb** [wix/wix-restaurants-api#13]
Previously working application started throwing the exception below since 12th July 2018. The app instance id and restaurant id are valid and set properly. Has anything changed in the wix restaurant internals?

com.wix.restaurants.authentication.exceptions.InternalException: null
	at com.wix.restaurants.authentication.DefaultWixRestaurantsAuthenticationClient.request(DefaultWixRestaurantsAuthenticationClient.java:117) ~[wix-restaurants-authentication-client-1.5.0.jar!/:na]
	at com.wix.restaurants.authentication.DefaultWixRestaurantsAuthenticationClient.loginWithWixInstance(DefaultWixRestaurantsAuthenticationClient.java:90) ~[wix-restaurants-authentication-client-1.5.0.jar!/:na]
	at com.achernartech.wixprinter.services.impl.PrinterServiceImpl.getNewOrdersFromApi(PrinterServiceImpl.java:93) ~[classes!/:1.6.0]
	at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
Caused by: com.wix.restaurants.jsonclient.JsonClientException: null
	at com.wix.restaurants.jsonclient.JsonClient.parseJsonResponse(JsonClient.java:57) ~[wix-restaurants-jsonclient-1.5.0.jar!/:na]
	at com.wix.restaurants.jsonclient.JsonClient.post(JsonClient.java:49) ~[wix-restaurants-jsonclient-1.5.0.jar!/:na]
	at com.wix.restaurants.authentication.DefaultWixRestaurantsAuthenticationClient.request(DefaultWixRestaurantsAuthenticationClient.java:109) ~[wix-restaurants-authentication-client-1.5.0.jar!/:na]
	... 14 common frames omitted

**Comment by dleshem** [comment]
Can you update your dependencies to the latest version of wix-restaurants-java-sdk (see here: https://github.com/wix/wix-restaurants-java-sdk) and try again?

**Comment by ravithb** [comment]
Hi dlshem,

Thanks for your reply. I did update to 1.20.0 and now this.

nested exception is java.lang.NoSuchMethodError: scala.Product.$init$(Lscala/Product;)V

Was there any dependency change in scala libraries in the sdk, when it was upgraded from 1.17.0 to 1.20.0, Can you point me to a migration guide if any?

**Comment by dleshem** [comment]
Yes, there was.

How are you managing dependencies in your project? With maven you should get it automatically.

**Comment by ravithb** [comment]
Yes, I'm using maven. But that didn't seem to work. Can you tell me which version so that it can be included explicitly ?

**Comment by dleshem** [comment]
`mvn dependency:tree` output:

```
[INFO] com.wix.restaurants:wix-restaurants-java-client:jar:1.20.0
[INFO] +- com.wix.restaurants:wix-restaurants-api:jar:1.20.0:compile
[INFO] |  \- com.wix.openrest:openrest4j-api:jar:1.32.0:compile
[INFO] |     +- com.fasterxml.jackson.core:jackson-core:jar:2.9.5:compile
[INFO] |     +- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.5:compile
[INFO] |     +- com.wix.restaurants:wix-restaurants-availability-api:jar:1.9.0:compile
[INFO] |     \- com.wix.pay:smaug-client-api:jar:1.8.0:compile
[INFO] |        +- com.wix.pay:credit-card:jar:1.8.0:compile
[INFO] |        |  \- com.wix.pay:credit-card-networks:jar:1.4.0:compile
[INFO] |        \- com.wix.restaurants:common-protocol-api:jar:1.12.0:compile
[INFO] +- com.wix.restaurants:wix-restaurants-authentication-client:jar:1.12.0:compile
[INFO] |  +- com.wix.restaurants:wix-restaurants-authentication-api:jar:1.12.0:compile
[INFO] |  \- com.wix.restaurants:wix-restaurants-json:jar:1.7.0:compile
[INFO] |     \- org.slf4j:slf4j-api:jar:1.7.25:compile
[INFO] +- com.wix.rest:rest-rfc7807-client:jar:1.0.0:compile
[INFO] |  +- com.wix.rest:rest-rfc7807-api:jar:1.0.0:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.9.5:compile
[INFO] |  +- com.fasterxml.jackson.module:jackson-module-scala_2.12:jar:2.9.5:compile
[INFO] |  |  \- com.fasterxml.jackson.module:jackson-module-paranamer:jar:2.9.5:compile
[INFO] |  |     \- com.thoughtworks.paranamer:paranamer:jar:2.8:compile
[INFO] |  +- com.fasterxml.jackson.datatype:jackson-datatype-guava:jar:2.9.5:compile
[INFO] |  |  \- com.google.guava:guava:jar:18.0:compile
[INFO] |  +- com.fasterxml.jackson.datatype:jackson-datatype-joda:jar:2.9.5:compile
[INFO] |  |  \- joda-time:joda-time:jar:2.7:compile
[INFO] |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.9.5:compile
[INFO] |  +- com.typesafe.akka:akka-http_2.12:jar:10.1.1:compile
[INFO] |  |  \- com.typesafe.akka:akka-http-core_2.12:jar:10.1.1:compile
[INFO] |  |     \- com.typesafe.akka:akka-parsing_2.12:jar:10.1.1:compile
[INFO] |  \- com.typesafe.akka:akka-stream_2.12:jar:2.5.12:compile
[INFO] |     +- com.typesafe.akka:akka-actor_2.12:jar:2.5.12:compile
[INFO] |     |  +- com.typesafe:config:jar:1.3.2:compile
[INFO] |     |  \- org.scala-lang.modules:scala-java8-compat_2.12:jar:0.8.0:compile
[INFO] |     +- com.typesafe.akka:akka-protobuf_2.12:jar:2.5.12:compile
[INFO] |     +- org.reactivestreams:reactive-streams:jar:1.0.2:compile
[INFO] |     \- com.typesafe:ssl-config-core_2.12:jar:0.2.3:compile
[INFO] |        \- org.scala-lang.modules:scala-parser-combinators_2.12:jar:1.1.0:compile
[INFO] +- org.scala-lang:scala-reflect:jar:2.12.4:compile
[INFO] |  \- org.scala-lang:scala-library:jar:2.12.4:compile
```

**Comment by ravithb** [comment]
Ok. Thanks. Upgrading to openrest4j 1.32 fixed the problem.
