### ISSUE TITLE
Incorrect auth api url in examples 

### ISSUE THREAD

**Issue by ravithb** [wix/wix-restaurants-api#14]
The line 105 of https://github.com/wix/wix-restaurants-java-sdk/blob/master/wix-restaurants-java-examples/src/main/java/com/wix/restaurants/examples/SubmitOrderExample.java is incorrect, needs to be /v2 otherwise it causes the following exception.
`
```
com.wix.rest.rfc7807.client.exception.ProtocolException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /v1/com.wix/access_token</pre>
</body>
</html>
; line: 1, column: 2]
	at com.wix.rest.rfc7807.client.AkkaRestClient$ExecuteResponseContext$$anonfun$extractResponse$3.applyOrElse(AkkaRestClient.scala:65) ~[rest-rfc7807-client-1.0.0.jar!/:na]
	at com.wix.rest.rfc7807.client.AkkaRestClient$ExecuteResponseContext$$anonfun$extractResponse$3.applyOrElse(AkkaRestClient.scala:63) ~[rest-rfc7807-client-1.0.0.jar!/:na]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34) ~[scala-library-2.12.4.jar!/:na]
	at scala.util.Failure.recover(Try.scala:230) ~[scala-library-2.12.4.jar!/:na]
	at scala.concurrent.Future.$anonfun$recover$1(Future.scala:392) ~[scala-library-2.12.4.jar!/:na]
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29) ~[scala-library-2.12.4.jar!/:na]
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29) ~[scala-library-2.12.4.jar!/:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60) ~[scala-library-2.12.4.jar!/:na]
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) ~[akka-actor_2.12-2.5.12.jar!/:2.5.12]
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91) ~[akka-actor_2.12-2.5.12.jar!/:2.5.12]
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12) ~[scala-library-2.12.4.jar!/:na]
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81) ~[scala-library-2.12.4.jar!/:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91) ~[akka-actor_2.12-2.5.12.jar!/:2.5.12]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) ~[akka-actor_2.12-2.5.12.jar!/:2.5.12]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44) ~[akka-actor_2.12-2.5.12.jar!/:2.5.12]
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[akka-actor_2.12-2.5.12.jar!/:2.5.12]
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[akka-actor_2.12-2.5.12.jar!/:2.5.12]
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[akka-actor_2.12-2.5.12.jar!/:2.5.12]
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[akka-actor_2.12-2.5.12.jar!/:2.5.12]
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /v1/com.wix/access_token</pre>
</body>
</html>
; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702) ~[jackson-core-2.8.10.jar!/:2.8.10]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558) ~[jackson-core-2.8.10.jar!/:2.8.10]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:456) ~[jackson-core-2.8.10.jar!/:2.8.10]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1906) ~[jackson-core-2.8.10.jar!/:2.8.10]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:749) ~[jackson-core-2.8.10.jar!/:2.8.10]
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3850) ~[jackson-databind-2.8.10.jar!/:2.8.10]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3799) ~[jackson-databind-2.8.10.jar!/:2.8.10]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2858) ~[jackson-databind-2.8.10.jar!/:2.8.10]
	at com.wix.rest.rfc7807.client.JsonMapper$.jsonStringTo(JsonMapper.scala:22) ~[rest-rfc7807-client-1.0.0.jar!/:na]
	at com.wix.rest.rfc7807.client.JsonMapper$Implicits$JsonString2Object.as(JsonMapper.scala:36) ~[rest-rfc7807-client-1.0.0.jar!/:na]
	at com.wix.rest.rfc7807.client.AkkaRestClient.$anonfun$unmarshal$1(AkkaRestClient.scala:42) ~[rest-rfc7807-client-1.0.0.jar!/:na]
	at scala.util.Success.$anonfun$map$1(Try.scala:251) ~[scala-library-2.12.4.jar!/:na]
	at scala.util.Success.map(Try.scala:209) ~[scala-library-2.12.4.jar!/:na]
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:289) ~[scala-library-2.12.4.jar!/:na]
	at akka.http.scaladsl.util.FastFuture$FulfilledFuture.transform(FastFuture.scala:84) ~[akka-http-core_2.12-10.1.1.jar!/:10.1.1]
	at scala.concurrent.Future.map(Future.scala:289) ~[scala-library-2.12.4.jar!/:na]
	at scala.concurrent.Future.map$(Future.scala:289) ~[scala-library-2.12.4.jar!/:na]
	at akka.http.scaladsl.util.FastFuture$FulfilledFuture.map(FastFuture.scala:77) ~[akka-http-core_2.12-10.1.1.jar!/:10.1.1]
	at com.wix.rest.rfc7807.client.AkkaRestClient.unmarshal(AkkaRestClient.scala:42) ~[rest-rfc7807-client-1.0.0.jar!/:na]
	at com.wix.rest.rfc7807.client.AkkaRestClient.$anonfun$execute$2(AkkaRestClient.scala:27) ~[rest-rfc7807-client-1.0.0.jar!/:na]
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:304) ~[scala-library-2.12.4.jar!/:na]
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37) ~[scala-library-2.12.4.jar!/:na]
	... 12 common frames omitted

```

**Comment by dleshem** [comment]
Thanks! Fixed in https://github.com/wix/wix-restaurants-java-sdk/commit/7b86bbc38e5316f618113066f7e72640da1ffa8a.
